# Generated by Django 5.2.7 on 2025-10-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='data_geracao_pdf',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Geração do PDF'),
        ),
        migrations.AddField(
            model_name='documento',
            name='formato_documento',
            field=models.CharField(choices=[('completo', 'Completo (Receita + Rótulo)'), ('rotulo_apenas', 'Apenas Rótulo Nutricional'), ('receita_apenas', 'Apenas Receita')], default='completo', max_length=20, verbose_name='Formato do Documento'),
        ),
        migrations.AddField(
            model_name='documento',
            name='pdf_gerado',
            field=models.BooleanField(default=False, verbose_name='PDF Gerado'),
        ),
        migrations.AddField(
            model_name='receita',
            name='formato_rotulo',
            field=models.CharField(choices=[('vertical', 'Vertical'), ('horizontal', 'Horizontal'), ('quebrado_vertical', 'Quebrado Vertical'), ('quebrado_horizontal', 'Quebrado Horizontal')], default='vertical', max_length=20, verbose_name='Formato do Rótulo'),
        ),
        migrations.AddField(
            model_name='receita',
            name='habilitar_rotulo_nutricional',
            field=models.BooleanField(default=False, verbose_name='Habilitar Rótulo Nutricional'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='arquivo_pdf',
            field=models.FileField(blank=True, help_text='PDF contendo ficha técnica, rótulos e precificação', null=True, upload_to='documentos/%Y/%m/', verbose_name='Arquivo PDF'),
        ),
    ]
