# Generated by Django 5.2.7 on 2025-10-26 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='avatar',
            field=models.URLField(blank=True, null=True, verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='google_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Google ID'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='login_social',
            field=models.CharField(choices=[('manual', 'Manual'), ('google', 'Google')], default='manual', max_length=20, verbose_name='Login Social'),
        ),
    ]
