# Generated by Django 5.2.7 on 2025-11-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='medida_caseira',
            field=models.CharField(help_text='Ex: 1 xícara de chá, 2 colheres de sopa, 1 fatia, etc.', max_length=100, null=True, verbose_name='Medida Caseira'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='porcao_individual',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Porção Individual (g/ml)'),
        ),
    ]
