# Generated by Django 5.2.7 on 2025-11-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_documento_data_geracao_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome do Usuário'),
        ),
    ]
