# Generated by Django 5.2.7 on 2025-11-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_usuario_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='avatar_url',
        ),
        migrations.AddField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
