from .AlimentoTacoSerializers import AlimentoTacoSerializer
from .RotuloNutricionalSerializers import RotuloNutricionalSerializer
from .ReceitaSerializers import ReceitaSerializer
from .IngredienteSerializers import IngredienteSerializer, IngredienteListSerializer
from .RotuloNutricionalSerializers import RotuloNutricionalSerializer, DocumentoCreateSerializer